name: biletfy_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.13.2

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  intl: ^0.20.3
  lucide_icons_flutter: ^3.1.17
  share_plus: 13.3.0
  shimmer: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bkm-logo.png
    - assets/images/events/
